module.exports = {
  logdir: "logs",
  debuglog: "/debug.log",
  tracelog: "/trace.log",
  infolog: "/info.log",
  errlog: "/err.log",
  warnlog: "/warn.log",
  datalog: "/ldata.log",
  cookiename: "kindah",
  host: "localhost",
  port: 8080,
  url: "http://",
  // serviceURL: "https://kindahclinic.com/KindahService/",
  serviceURL: "http://localhost:1042/KindahService/",
  max_length: 50,
  name: "Kindah",
};
